
const productos = [ 
                    { id: 0,
                      nombre: "Camiseta Barcelona Titular", 
                      precio: 9500,
                      descripcion: "Camiseta Nike Fc Barcelona 2021/22 Stadium Home",
                      categoria: "Camisetas",
                      url: "/imagenes/camiseta.png",
                      stock: 10},
                    { id: 1,
                      nombre: "Short Barcelona Titular",
                      precio: 3000,
                      descripcion: "Nike Pantalon Corto FC Barcelona Stadium Primera/Segunda Equipación 21/22",
                      categoria: "Shorts",
                      url: "/imagenes/shortbarsa.png",
                      stock: 6},
                    { id: 2,
                      nombre: "Camiseta Titular Manchester City", 
                      precio: 7000,
                      descripcion: "Camiseta titular  Manchester City",
                      categoria: "Camisetas",
                      url: "/imagenes/camisetacity.png",
                      stock: 3},
                    { id: 3,
                      nombre: "Medias Futbol",
                      precio: 1200,
                      descripcion: "Medias adidas Milano 16",
                      categoria: "Otros",
                      url: "/imagenes/mediasnegras.png",
                      stock: 23},    
                    { id: 4,
                      nombre: "Guantes Arquero",
                      precio: 4500,
                      descripcion: "Guantes De Arquero Rinat Uno Premier",
                      categoria: "Otros",
                      url: "/imagenes/guantes.png",
                      stock: 11},    
                    { id: 5,
                      nombre: "Medias Suplente Borussia Dormunt",
                      precio: 2800,
                      descripcion: "Medias suplente borussia Dormunt 2022",
                      categoria: "Otros",
                      url: "/imagenes/mediasdormunt.png",
                      stock: 2},    
                    { id: 6,
                      nombre: "Camiseta Banfield Titular",
                      precio: 6700,
                      descripcion: "Camiseta Club Atletico Banfield titular temporada 2021",
                      categoria: "Camisetas",
                      url: "/imagenes/camisetabanfield.png",
                      stock: 2},    
                    { id: 7,
                      nombre: "Short Real Madrid Titular",
                      precio: 3500,
                      descripcion: "Short Real Madrid titular temporada 2021",
                      categoria: "Shorts",
                      url: "/imagenes/shortreal.png",
                      stock: 7}] ;

export default productos ;